# Generated by Django 3.2 on 2021-11-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'accounts', 'verbose_name_plural': 'account'},
        ),
    ]
